version: "3"
services:
  enigma-socket:
    build:
      context: .
    image: enigma-socket
    container_name: enigma-socket
    hostname: enigma-socket
    ports:
      - "6001:6001"
    expose:
      - "6001"
    restart: unless-stopped

networks:
  enigma-network:
    name: enigma-network