version: "3"
services:
  socket:
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    ports:
      - "6001:6001"
    expose:
      - "6001"
    env_file:
      - .env
    volumes:
      - ../:/app
    restart: unless-stopped