version: "3"
services:
  socket:
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "6001:6001"
    expose:
      - "6001"
    volumes:
      - ../:/app
    restart: unless-stopped